package com.jhw.swing.examples.components.login_and_dashboard;

import com.jhw.swing.notification.fade.NotificationDialogGeneral;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.jhw.swing.ui.MaterialLookAndFeel;
import com.jhw.swing.util.Utils;
import com.jhw.swing.material.standars.MaterialColors;
import com.jhw.swing.material.standars.MaterialIcons;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class LOGIN_DASH_EXAMPLE extends javax.swing.JFrame {

    public LOGIN_DASH_EXAMPLE() {
        initComponents();

        this.setIconImage(MaterialIcons.SETTINGS.getImage());
        this.setTitle("Meca ver.1.11.0");

        addClosingEvent();
        personalize();

        //if (cfg.isChangeToLogin()) {//this is a litle back door for not login in dev
        changeToLogin();
        //} else {
        //    changeToDashBoard();
        //}

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _PanelGradientBackground = new com.jhw.swing.material.components.container.panel._PanelGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meca");

        _PanelGradientBackground.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_PanelGradientBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_PanelGradientBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jhw.swing.material.components.container.panel._PanelGradient _PanelGradientBackground;
    // End of variables declaration//GEN-END:variables

    private void personalize() {
        this.setSize(Utils.getScreenSize().getSize());
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);//maximize the window
    }

    private void changeToLogin() {
        LoginView login = new LoginView();

        login.addLoginAction(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                boolean resp = login.login();
                login.setUpAnswer(resp);
                if (resp) {
                    new NotificationDialogGeneral(3,
                            "welcome back user",
                            MaterialIcons.VISIBILITY,
                            MaterialColors.BLUE_400);
                    changeToDashBoard();
                }

            }
        });

        putComponent(login);
    }

    private void changeToDashBoard() {
        DashboardView dash = new DashboardView();
        putComponent(dash);
    }

    private void putComponent(Component comp) {
        _PanelGradientBackground.removeAll();
        _PanelGradientBackground.add(comp);
        _PanelGradientBackground.repaint();
    }

    private void addClosingEvent() {
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                System.out.println("Do something if the windows is closing, like close the db service");
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new MaterialLookAndFeel());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_DASH_EXAMPLE().setVisible(true);
            }
        });
    }
}
