package com.jhw.swing.examples.standars;

import com.jhw.swing.material.components.labels._MaterialLabel;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.jhw.swing.ui.MaterialLookAndFeel;
import com.jhw.swing.util.Utils;
import com.jhw.swing.utils.icons.DerivableIcon;
import com.jhw.swing.utils.icons.IconTTF;
import com.jhw.swing.material.standards.MaterialIcons;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class MATERIAL_ICONS_EXAMPLE extends javax.swing.JFrame {

    public static final Field[] fields = MaterialIcons.class.getDeclaredFields();

    public static DerivableIcon getRandomIcon() {
        DerivableIcon c = null;
        for (int i = 0; i < 1000; i++) {
            try {
                c = (DerivableIcon) fields[new Random().nextInt(fields.length)].get(null);
                return c;
            } catch (Exception e) {
            }
        }
        return MaterialIcons.ADD;
    }

    public MATERIAL_ICONS_EXAMPLE() {
        initComponents();
        Arrays.sort(fields, new Comparator<Field>() {
            @Override
            public int compare(Field o1, Field o2) {
                return o1.getName().compareToIgnoreCase(o2.getName());
            }
        });

        for (Field field : fields) {
            if (Modifier.isStatic(field.getModifiers())
                    && DerivableIcon.class.isAssignableFrom(field.getType())) {
                try {
                    DerivableIcon c = (DerivableIcon) field.get(null);
                    String name = field.getName();
                    _MaterialLabel l = new _MaterialLabel();
                    l.setIcon(c);
                    l.setToolTipText(name);
                    this._PanelGradient1.add(l);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }

        this.setSize(Utils.getScreenSize().getSize());
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);//maximize the window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//
    private void initComponents() {

        _PanelGradient1 = new com.jhw.swing.material.components.container.panel._PanelGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _PanelGradient1.setPrimaryColor(new java.awt.Color(204, 204, 204));
        _PanelGradient1.setSecundaryColor(new java.awt.Color(204, 204, 204));
        _PanelGradient1.setLayout(new java.awt.GridLayout(0, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_PanelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_PanelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new MaterialLookAndFeel());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MATERIAL_ICONS_EXAMPLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//:variables
    private com.jhw.swing.material.components.container.panel._PanelGradient _PanelGradient1;
    // End of variables declaration                   

}
