package com.jhw.swing.notification.fade;

import com.jhw.swing.material.components.textarea._ContentArea;
import com.jhw.swing.material.components.button._MaterialIconButtonTranspRect;
import com.jhw.swing.material.components.container.panel._MaterialPanel;
import com.jhw.swing.material.components.labels._MaterialLabel;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import com.jhw.swing.material.standars.MaterialIcons;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class NotificationPanel extends _MaterialPanel {

    public NotificationPanel(String header, Font headerFont, String text, Font textFont, ImageIcon icon, Color color) {
        initComponents();

        this.setBackground(color);
        contentArea.setBackColor(color);
        contentArea.setHeaderFont(headerFont);
        contentArea.setHeader(header);
        contentArea.setTextFont(textFont);
        contentArea.setText(text);
        buttonClose.setIcon(MaterialIcons.CLOSE.deriveIcon(18f));
        setIcon(icon);
    }

    public NotificationPanel(String header, String text, ImageIcon icon, Color color) {
        initComponents();

        this.setBackground(color);
        contentArea.setBackColor(color);
        contentArea.setHeader(header);
        contentArea.setText(text);
        setIcon(icon);
    }

    private void setIcon(ImageIcon icon) {
        labelIcon.setBackground(contentArea.getBackColor());
        labelIcon.setIcon(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIcon = new com.jhw.swing.material.components.labels._MaterialLabel();
        buttonClose = new com.jhw.swing.material.components.button._MaterialIconButtonTranspRect();
        contentArea = new com.jhw.swing.material.components.textarea._ContentArea();

        setBorderRadius(3);

        buttonClose.setText("_MaterialIconButtonTranspRect1");

        contentArea.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(contentArea, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jhw.swing.material.components.button._MaterialIconButtonTranspRect buttonClose;
    private com.jhw.swing.material.components.textarea._ContentArea contentArea;
    private com.jhw.swing.material.components.labels._MaterialLabel labelIcon;
    // End of variables declaration//GEN-END:variables

    public _MaterialLabel getMaterialLabel1() {
        return labelIcon;
    }

    public void setMaterialLabel1(_MaterialLabel _MaterialLabel1) {
        this.labelIcon = _MaterialLabel1;
    }

    public _MaterialIconButtonTranspRect getMaterialIconButtonTranspRect1() {
        return buttonClose;
    }

    public void setMaterialIconButtonTranspRect1(_MaterialIconButtonTranspRect _MaterialIconButtonTranspRect1) {
        this.buttonClose = _MaterialIconButtonTranspRect1;
    }

    public _MaterialIconButtonTranspRect getButtonClose() {
        return buttonClose;
    }

    public void setButtonClose(_MaterialIconButtonTranspRect buttonClose) {
        this.buttonClose = buttonClose;
    }

    public _ContentArea getContentArea() {
        return contentArea;
    }

    public void setContentArea(_ContentArea contentArea) {
        this.contentArea = contentArea;
    }

    public _MaterialLabel getLabelIcon() {
        return labelIcon;
    }

    public void setLabelIcon(_MaterialLabel labelIcon) {
        this.labelIcon = labelIcon;
    }

}
