package com.jhw.swing.material.components.button;

import com.jhw.swing.material.components.container.panels._MaterialPanel;
import com.jhw.swing.material.components.container.panels._PanelTransparent;
import com.jhw.swing.material.standars.MaterialColors;
import com.jhw.swing.material.standars.MaterialIcons;

/**
 *
 * @author Jesús Hernández Barrios (jhernandezb96@gmail.com)
 */
public class _MaterialButtonDouble extends _PanelTransparent {

    public _MaterialButtonDouble() {
        initComponents();
        personalize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new com.jhw.swing.material.components.container.panels._MaterialPanel();
        buttonLeft = new com.jhw.swing.material.components.button._MaterialButtonSimpleIcon();
        buttonRight = new com.jhw.swing.material.components.button._MaterialButtonSimpleIcon();

        panelBackground.setBackground(new java.awt.Color(204, 204, 204));
        panelBackground.setBorderRadius(2);
        panelBackground.setPreferredSize(new java.awt.Dimension(120, 35));

        buttonLeft.setBackground(new java.awt.Color(255, 255, 255));
        buttonLeft.setBorderRadius(2);

        buttonRight.setBackground(new java.awt.Color(255, 255, 255));
        buttonRight.setBorderRadius(2);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(buttonRight, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(buttonRight, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jhw.swing.material.components.button._MaterialButtonSimpleIcon buttonLeft;
    private com.jhw.swing.material.components.button._MaterialButtonSimpleIcon buttonRight;
    private com.jhw.swing.material.components.container.panels._MaterialPanel panelBackground;
    // End of variables declaration//GEN-END:variables

    private void personalize() {
        buttonLeft.setIcon(MaterialIcons.KEYBOARD_ARROW_LEFT);
        buttonLeft.getFadeinto().setAccent(MaterialColors.GREY_200);
        buttonLeft.setRippleColor(MaterialColors.GREY_300);

        buttonRight.setIcon(MaterialIcons.KEYBOARD_ARROW_RIGHT);
        buttonRight.getFadeinto().setAccent(MaterialColors.GREY_200);
        buttonRight.setRippleColor(MaterialColors.GREY_300);
    }

    public _MaterialButtonSimpleIcon getButtonLeft() {
        return buttonLeft;
    }

    public _MaterialButtonSimpleIcon getButtonRight() {
        return buttonRight;
    }

    public _MaterialPanel getPanelBackground() {
        return panelBackground;
    }

}
