package com.jhw.swing.examples.components.containers;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.jhw.swing.ui.MaterialLookAndFeel;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class TABBED_EXAMPLE extends javax.swing.JFrame {

    public TABBED_EXAMPLE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//
    private void initComponents() {

        _TabbedPaneClose1 = new com.jhw.swing.material.components.container.tabbed._TabbedPaneClose();
        _MaterialPanel1 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel2 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel3 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _TabbedPaneHeader1 = new com.jhw.swing.material.components.container.tabbed._TabbedPaneHeader();
        _MaterialPanel4 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel5 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel6 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _TabbedPaneSelector1 = new com.jhw.swing.material.components.container.tabbed._TabbedPaneSelector();
        _MaterialPanel7 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel8 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel9 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        _MaterialPanel10 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel11 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel12 = new com.jhw.swing.material.components.container.panel._MaterialPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout _MaterialPanel1Layout = new javax.swing.GroupLayout(_MaterialPanel1);
        _MaterialPanel1.setLayout(_MaterialPanel1Layout);
        _MaterialPanel1Layout.setHorizontalGroup(
            _MaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        _MaterialPanel1Layout.setVerticalGroup(
            _MaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        _TabbedPaneClose1.addTab("tab1", _MaterialPanel1);

        javax.swing.GroupLayout _MaterialPanel2Layout = new javax.swing.GroupLayout(_MaterialPanel2);
        _MaterialPanel2.setLayout(_MaterialPanel2Layout);
        _MaterialPanel2Layout.setHorizontalGroup(
            _MaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        _MaterialPanel2Layout.setVerticalGroup(
            _MaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        _TabbedPaneClose1.addTab("tab2", _MaterialPanel2);

        javax.swing.GroupLayout _MaterialPanel3Layout = new javax.swing.GroupLayout(_MaterialPanel3);
        _MaterialPanel3.setLayout(_MaterialPanel3Layout);
        _MaterialPanel3Layout.setHorizontalGroup(
            _MaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        _MaterialPanel3Layout.setVerticalGroup(
            _MaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        _TabbedPaneClose1.addTab("tab3", _MaterialPanel3);

        javax.swing.GroupLayout _MaterialPanel4Layout = new javax.swing.GroupLayout(_MaterialPanel4);
        _MaterialPanel4.setLayout(_MaterialPanel4Layout);
        _MaterialPanel4Layout.setHorizontalGroup(
            _MaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        _MaterialPanel4Layout.setVerticalGroup(
            _MaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        _TabbedPaneHeader1.addTab("tab1", _MaterialPanel4);

        javax.swing.GroupLayout _MaterialPanel5Layout = new javax.swing.GroupLayout(_MaterialPanel5);
        _MaterialPanel5.setLayout(_MaterialPanel5Layout);
        _MaterialPanel5Layout.setHorizontalGroup(
            _MaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        _MaterialPanel5Layout.setVerticalGroup(
            _MaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        _TabbedPaneHeader1.addTab("tab2", _MaterialPanel5);

        javax.swing.GroupLayout _MaterialPanel6Layout = new javax.swing.GroupLayout(_MaterialPanel6);
        _MaterialPanel6.setLayout(_MaterialPanel6Layout);
        _MaterialPanel6Layout.setHorizontalGroup(
            _MaterialPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        _MaterialPanel6Layout.setVerticalGroup(
            _MaterialPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        _TabbedPaneHeader1.addTab("tab3", _MaterialPanel6);

        javax.swing.GroupLayout _MaterialPanel7Layout = new javax.swing.GroupLayout(_MaterialPanel7);
        _MaterialPanel7.setLayout(_MaterialPanel7Layout);
        _MaterialPanel7Layout.setHorizontalGroup(
            _MaterialPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        _MaterialPanel7Layout.setVerticalGroup(
            _MaterialPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        _TabbedPaneSelector1.addTab("tab1", _MaterialPanel7);

        javax.swing.GroupLayout _MaterialPanel8Layout = new javax.swing.GroupLayout(_MaterialPanel8);
        _MaterialPanel8.setLayout(_MaterialPanel8Layout);
        _MaterialPanel8Layout.setHorizontalGroup(
            _MaterialPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        _MaterialPanel8Layout.setVerticalGroup(
            _MaterialPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        _TabbedPaneSelector1.addTab("tab2", _MaterialPanel8);

        javax.swing.GroupLayout _MaterialPanel9Layout = new javax.swing.GroupLayout(_MaterialPanel9);
        _MaterialPanel9.setLayout(_MaterialPanel9Layout);
        _MaterialPanel9Layout.setHorizontalGroup(
            _MaterialPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        _MaterialPanel9Layout.setVerticalGroup(
            _MaterialPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        _TabbedPaneSelector1.addTab("tab3", _MaterialPanel9);

        javax.swing.GroupLayout _MaterialPanel10Layout = new javax.swing.GroupLayout(_MaterialPanel10);
        _MaterialPanel10.setLayout(_MaterialPanel10Layout);
        _MaterialPanel10Layout.setHorizontalGroup(
            _MaterialPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        _MaterialPanel10Layout.setVerticalGroup(
            _MaterialPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", _MaterialPanel10);

        javax.swing.GroupLayout _MaterialPanel11Layout = new javax.swing.GroupLayout(_MaterialPanel11);
        _MaterialPanel11.setLayout(_MaterialPanel11Layout);
        _MaterialPanel11Layout.setHorizontalGroup(
            _MaterialPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        _MaterialPanel11Layout.setVerticalGroup(
            _MaterialPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", _MaterialPanel11);

        javax.swing.GroupLayout _MaterialPanel12Layout = new javax.swing.GroupLayout(_MaterialPanel12);
        _MaterialPanel12.setLayout(_MaterialPanel12Layout);
        _MaterialPanel12Layout.setHorizontalGroup(
            _MaterialPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 233, Short.MAX_VALUE)
        );
        _MaterialPanel12Layout.setVerticalGroup(
            _MaterialPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", _MaterialPanel12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(_TabbedPaneClose1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_TabbedPaneSelector1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_TabbedPaneHeader1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(_TabbedPaneHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(_TabbedPaneClose1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_TabbedPaneSelector1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new MaterialLookAndFeel());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TABBED_EXAMPLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//:variables
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel1;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel10;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel11;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel12;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel2;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel3;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel4;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel5;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel6;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel7;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel8;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel9;
    private com.jhw.swing.material.components.container.tabbed._TabbedPaneClose _TabbedPaneClose1;
    private com.jhw.swing.material.components.container.tabbed._TabbedPaneHeader _TabbedPaneHeader1;
    private com.jhw.swing.material.components.container.tabbed._TabbedPaneSelector _TabbedPaneSelector1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
