package com.jhw.swing.examples.notification;

import com.jhw.swing.notification.toast.DialogToast;
import com.jhw.swing.notification.toast.TOAST;
import com.jhw.swing.notification.toast.types.notification.DialogNotificationToastGeneral;
import com.jhw.swing.notification.toast.types.text.DialogTextToastGeneral;
import com.jhw.swing.notification.toast.types.text.TextToast;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.jhw.swing.ui.MaterialLookAndFeel;
import com.jhw.swing.material.standars.MaterialColors;
import com.jhw.swing.material.standars.MaterialIcons;
import com.jhw.swing.material.standars.MaterialImages;

/**
 *
 * @author Jesús Hernández Barrios (jhernandezb96@gmail.com)
 */
public class TOAST_EXAMPLE extends javax.swing.JFrame {

    public TOAST_EXAMPLE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _MaterialButton1 = new com.jhw.swing.material.components.button._MaterialButton();
        _MaterialButton2 = new com.jhw.swing.material.components.button._MaterialButton();
        _MaterialButton3 = new com.jhw.swing.material.components.button._MaterialButton();
        _MaterialButton4 = new com.jhw.swing.material.components.button._MaterialButton();
        _MaterialButton5 = new com.jhw.swing.material.components.button._MaterialButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _MaterialButton1.setText("TOAST NOTIF");
        _MaterialButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton1ActionPerformed(evt);
            }
        });

        _MaterialButton2.setText("TOAST TEXT");
        _MaterialButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton2ActionPerformed(evt);
            }
        });

        _MaterialButton3.setText("TOAST NOTIF GENERAL");
        _MaterialButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton3ActionPerformed(evt);
            }
        });

        _MaterialButton4.setText("TOAST TEXT GENERAL");
        _MaterialButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton4ActionPerformed(evt);
            }
        });

        _MaterialButton5.setText("GENERAL");
        _MaterialButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _MaterialButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_MaterialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_MaterialButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(_MaterialButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_MaterialButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(_MaterialButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_MaterialButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_MaterialButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(_MaterialButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_MaterialButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_MaterialButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _MaterialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton1ActionPerformed
        TOAST.makeNotificationInfo("Hello world,\n ...\n...\n...\n... i'm a notification info toast.");
    }//GEN-LAST:event__MaterialButton1ActionPerformed

    private void _MaterialButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton2ActionPerformed
        TOAST.makeText("HI, i'm a text toast.");
    }//GEN-LAST:event__MaterialButton2ActionPerformed

    private void _MaterialButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton3ActionPerformed
        new DialogNotificationToastGeneral(3, "Notif toast general", MaterialIcons._3D_ROTATION, MaterialColors.AMBERA_400);
    }//GEN-LAST:event__MaterialButton3ActionPerformed

    private void _MaterialButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton4ActionPerformed
        new DialogTextToastGeneral(3, "Hollllllloooooooouuuuuuuuu");
    }//GEN-LAST:event__MaterialButton4ActionPerformed

    private void _MaterialButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__MaterialButton5ActionPerformed
        new DialogToast(3, new TextToast("SUPER GENERAL, middle of the screen"));
    }//GEN-LAST:event__MaterialButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new MaterialLookAndFeel());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TOAST_EXAMPLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jhw.swing.material.components.button._MaterialButton _MaterialButton1;
    private com.jhw.swing.material.components.button._MaterialButton _MaterialButton2;
    private com.jhw.swing.material.components.button._MaterialButton _MaterialButton3;
    private com.jhw.swing.material.components.button._MaterialButton _MaterialButton4;
    private com.jhw.swing.material.components.button._MaterialButton _MaterialButton5;
    // End of variables declaration//GEN-END:variables

}
