package com.jhw.swing.material.components.datepicker;

import com.jhw.swing.util.interfaces.DateSelected;
import com.jhw.swing.material.components.container.panel._PanelTransparent;
import java.util.Date;
import javax.swing.JComboBox;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class _MonthPicker extends _PanelTransparent implements DateSelected {

    private String[] meses = {"Enero", "Febrero", "Marzo", "Abril",
        "Mayo", "Junio", "Julio", "Agosto", "Septiempre", "Octubre", "Noviembre", "Diciembre"};

    private int minYear = 1900;
    private int maxYear = 3000;

    public _MonthPicker() {
        initComponents();
        setMonths();
        setYear();
        setActualDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxMonths = new javax.swing.JComboBox();
        comboBoxYear = new javax.swing.JComboBox();

        comboBoxMonths.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiempre", "Octubre", "Noviembre", "Diciembre" }));

        comboBoxYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(comboBoxMonths, 0, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboBoxMonths, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
            .addComponent(comboBoxYear)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBoxMonths;
    private javax.swing.JComboBox comboBoxYear;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(java.awt.event.ActionListener listener) {
        comboBoxMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listener.actionPerformed(evt);
            }
        });
        comboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listener.actionPerformed(evt);
            }
        });
    }

    private void setMonths() {
        comboBoxMonths.removeAllItems();
        for (String mes : meses) {
            comboBoxMonths.addItem(mes);
        }
    }

    public String[] getMeses() {
        return meses;
    }

    public void setMeses(String[] meses) {
        this.meses = meses;
    }

    private void setYear() {
        comboBoxYear.removeAllItems();
        for (int i = minYear; i <= maxYear; i++) {
            comboBoxYear.addItem(i);
        }
    }

    public int getMinYear() {
        return minYear;
    }

    public void setMinYear(int minYear) {
        this.minYear = minYear;
    }

    public int getMaxYear() {
        return maxYear;
    }

    public void setMaxYear(int maxYear) {
        this.maxYear = maxYear;
    }

    public JComboBox getComboBoxMonths() {
        return comboBoxMonths;
    }

    public void setComboBoxMonths(JComboBox comboBoxMonths) {
        this.comboBoxMonths = comboBoxMonths;
    }

    public JComboBox getComboBoxYear() {
        return comboBoxYear;
    }

    public void setComboBoxYear(JComboBox comboBoxYear) {
        this.comboBoxYear = comboBoxYear;
    }

    private void setActualDate() {
        Date hoy = new Date();
        comboBoxMonths.setSelectedIndex(hoy.getMonth());
        comboBoxYear.setSelectedIndex(hoy.getYear());
    }

    public int getSelectedYear() {
        return (int) comboBoxYear.getSelectedItem();
    }

    public int getSelectedMonth() {
        return comboBoxMonths.getSelectedIndex();
    }

    public String getSelectedMonthString() {
        return meses[getSelectedMonth()];
    }

    /**
     * Faltan por hacer las validaciones.
     *
     * @return
     */
    @Override
    public Date getDateValidated() {
        return new Date(getSelectedYear() - 1900, getSelectedMonth(), 1);
    }

    @Override
    public Date getDate() {
        return new Date(getSelectedYear() - 1900, getSelectedMonth(), 1);
    }

    @Override
    public void setDate(Date date) {
        comboBoxMonths.setSelectedIndex(date.getMonth());
        comboBoxYear.setSelectedItem(date.getYear() + 1900);
    }

    @Override
    public void setEnabled(boolean enabled) {
        this.comboBoxMonths.setEnabled(enabled);
        this.comboBoxYear.setEnabled(enabled);
        super.setEnabled(enabled);
    }

}
