package com.jhw.swing.examples.components;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.jhw.swing.ui.MaterialLookAndFeel;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class SCROLL_SMOOT_EXAMPLE extends javax.swing.JFrame {

    public SCROLL_SMOOT_EXAMPLE() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _MaterialScrollPaneCore1 = new com.jhw.swing.material.components.scrollpane._MaterialScrollPaneCore();
        _PanelGradient1 = new com.jhw.swing.material.components.container.panel._PanelGradient();
        _MaterialPanel1 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel3 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel4 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel5 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel6 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _PanelGradient2 = new com.jhw.swing.material.components.container.panel._PanelGradient();
        _MaterialPanel2 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel7 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel8 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel9 = new com.jhw.swing.material.components.container.panel._MaterialPanel();
        _MaterialPanel10 = new com.jhw.swing.material.components.container.panel._MaterialPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _PanelGradient1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout _MaterialPanel1Layout = new javax.swing.GroupLayout(_MaterialPanel1);
        _MaterialPanel1.setLayout(_MaterialPanel1Layout);
        _MaterialPanel1Layout.setHorizontalGroup(
            _MaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        _MaterialPanel1Layout.setVerticalGroup(
            _MaterialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel3.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel3Layout = new javax.swing.GroupLayout(_MaterialPanel3);
        _MaterialPanel3.setLayout(_MaterialPanel3Layout);
        _MaterialPanel3Layout.setHorizontalGroup(
            _MaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        _MaterialPanel3Layout.setVerticalGroup(
            _MaterialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel4.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel4Layout = new javax.swing.GroupLayout(_MaterialPanel4);
        _MaterialPanel4.setLayout(_MaterialPanel4Layout);
        _MaterialPanel4Layout.setHorizontalGroup(
            _MaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        _MaterialPanel4Layout.setVerticalGroup(
            _MaterialPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel5.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel5Layout = new javax.swing.GroupLayout(_MaterialPanel5);
        _MaterialPanel5.setLayout(_MaterialPanel5Layout);
        _MaterialPanel5Layout.setHorizontalGroup(
            _MaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        _MaterialPanel5Layout.setVerticalGroup(
            _MaterialPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel6.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel6Layout = new javax.swing.GroupLayout(_MaterialPanel6);
        _MaterialPanel6.setLayout(_MaterialPanel6Layout);
        _MaterialPanel6Layout.setHorizontalGroup(
            _MaterialPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        _MaterialPanel6Layout.setVerticalGroup(
            _MaterialPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout _PanelGradient1Layout = new javax.swing.GroupLayout(_PanelGradient1);
        _PanelGradient1.setLayout(_PanelGradient1Layout);
        _PanelGradient1Layout.setHorizontalGroup(
            _PanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_MaterialPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_MaterialPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_MaterialPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_MaterialPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(_MaterialPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        _PanelGradient1Layout.setVerticalGroup(
            _PanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_PanelGradient1Layout.createSequentialGroup()
                .addComponent(_MaterialPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_MaterialPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_MaterialPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(_MaterialPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(_MaterialPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        _MaterialScrollPaneCore1.setViewportView(_PanelGradient1);

        _PanelGradient2.setBackground(new java.awt.Color(255, 255, 255));

        _MaterialPanel2.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel2Layout = new javax.swing.GroupLayout(_MaterialPanel2);
        _MaterialPanel2.setLayout(_MaterialPanel2Layout);
        _MaterialPanel2Layout.setHorizontalGroup(
            _MaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        _MaterialPanel2Layout.setVerticalGroup(
            _MaterialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel7.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel7Layout = new javax.swing.GroupLayout(_MaterialPanel7);
        _MaterialPanel7.setLayout(_MaterialPanel7Layout);
        _MaterialPanel7Layout.setHorizontalGroup(
            _MaterialPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        _MaterialPanel7Layout.setVerticalGroup(
            _MaterialPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel8.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel8Layout = new javax.swing.GroupLayout(_MaterialPanel8);
        _MaterialPanel8.setLayout(_MaterialPanel8Layout);
        _MaterialPanel8Layout.setHorizontalGroup(
            _MaterialPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        _MaterialPanel8Layout.setVerticalGroup(
            _MaterialPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel9.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel9Layout = new javax.swing.GroupLayout(_MaterialPanel9);
        _MaterialPanel9.setLayout(_MaterialPanel9Layout);
        _MaterialPanel9Layout.setHorizontalGroup(
            _MaterialPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        _MaterialPanel9Layout.setVerticalGroup(
            _MaterialPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        _MaterialPanel10.setPreferredSize(new java.awt.Dimension(519, 167));

        javax.swing.GroupLayout _MaterialPanel10Layout = new javax.swing.GroupLayout(_MaterialPanel10);
        _MaterialPanel10.setLayout(_MaterialPanel10Layout);
        _MaterialPanel10Layout.setHorizontalGroup(
            _MaterialPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        _MaterialPanel10Layout.setVerticalGroup(
            _MaterialPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout _PanelGradient2Layout = new javax.swing.GroupLayout(_PanelGradient2);
        _PanelGradient2.setLayout(_PanelGradient2Layout);
        _PanelGradient2Layout.setHorizontalGroup(
            _PanelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_MaterialPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(_MaterialPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(_MaterialPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(_MaterialPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(_MaterialPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        _PanelGradient2Layout.setVerticalGroup(
            _PanelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(_PanelGradient2Layout.createSequentialGroup()
                .addComponent(_MaterialPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(_MaterialPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(_MaterialPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(_MaterialPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(_MaterialPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(_PanelGradient2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(_MaterialScrollPaneCore1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_MaterialScrollPaneCore1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new MaterialLookAndFeel());

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SCROLL_SMOOT_EXAMPLE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel1;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel10;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel2;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel3;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel4;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel5;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel6;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel7;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel8;
    private com.jhw.swing.material.components.container.panel._MaterialPanel _MaterialPanel9;
    private com.jhw.swing.material.components.scrollpane._MaterialScrollPaneCore _MaterialScrollPaneCore1;
    private com.jhw.swing.material.components.container.panel._PanelGradient _PanelGradient1;
    private com.jhw.swing.material.components.container.panel._PanelGradient _PanelGradient2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
