package com.jhw.swing.material.components.filechooser;

import com.jhw.swing.material.components.button._MaterialButton;
import com.jhw.swing.material.components.container.panels._PanelTransparent;
import com.jhw.swing.material.components.labels._MaterialLabel;
import java.awt.event.ActionListener;
import java.io.File;
import com.clean.core.utils.Update;
import com.jhw.swing.material.standars.MaterialColors;
import com.jhw.swing.material.standars.MaterialIcons;

/**
 *
 * @author Jesus Hernandez Barrios (jhernandezb96@gmail.com)
 */
public class _MaterialFileChooserPanel extends _PanelTransparent implements Update {

    private _MaterialFileChooser fc;
    private static File lastFile = new File("");

    public _MaterialFileChooserPanel() {
        initComponents();
        addListeners();
        personalize();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSeleccionados = new com.jhw.swing.material.components.labels._MaterialLabel();
        buttonAbrir = new com.jhw.swing.material.components.button._MaterialButton();
        buttonOpenFolder = new com.jhw.swing.material.components.button._MaterialIconButtonTranspRect();

        labelSeleccionados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSeleccionados.setText("Nada seleccionado");

        buttonAbrir.setBackground(new java.awt.Color(102, 102, 102));
        buttonAbrir.setText("Buscar");
        buttonAbrir.setPreferredSize(new java.awt.Dimension(120, 45));

        buttonOpenFolder.setText("_MaterialIconButtonTranspRect1");
        buttonOpenFolder.setRippleColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonOpenFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labelSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonOpenFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jhw.swing.material.components.button._MaterialButton buttonAbrir;
    private com.jhw.swing.material.components.button._MaterialIconButtonTranspRect buttonOpenFolder;
    private com.jhw.swing.material.components.labels._MaterialLabel labelSeleccionados;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        updateLabel();
    }

    public void isCreate(boolean create) {
        buttonOpenFolder.setVisible(!create);
    }

    public void addButtonOpenFolderAction(ActionListener action) {
        buttonOpenFolder.addActionListener(action);
    }

    private void personalize() {
        buttonOpenFolder.setIcon(MaterialIcons.FOLDER);

        buttonAbrir.setBackground(MaterialColors.GREY_700);
        buttonAbrir.setIcon(MaterialIcons.FIND_IN_PAGE);
    }

    public _MaterialButton getButtonAbrir() {
        return buttonAbrir;
    }

    public void setButtonAbrir(_MaterialButton buttonAbrir) {
        this.buttonAbrir = buttonAbrir;
    }

    public _MaterialLabel getLabelSeleccionados() {
        return labelSeleccionados;
    }

    public void setLabelSeleccionados(_MaterialLabel labelSeleccionados) {
        this.labelSeleccionados = labelSeleccionados;
    }

    public _MaterialFileChooser getFc() {
        return fc;
    }

    private void addListeners() {
        buttonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onButtonAbrirActionPerformed();
            }
        });
    }

    private void onButtonAbrirActionPerformed() {
        fc = new _MaterialFileChooser(lastFile);
        fc.addConfirmListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLabel();
            }
        });
    }

    public void clear() {
        if (fc != null) {
            fc.setSelectedFiles(null);
            updateLabel();
        }
    }

    public File[] getSelectedFiles() {
        if (fc == null) {
            return new File[0];
        } else {
            return fc.getSelectedFiles();
        }
    }

    private void updateLabel() {
        if (fc == null || fc.getSelectedFiles().length == 0) {
            labelSeleccionados.setText("Nada seleccionado");
            return;
        } else if (fc.getSelectedFiles().length == 1) {
            labelSeleccionados.setText("1: Seleccionado");
        } else {
            labelSeleccionados.setText("Seleccionados: " + fc.getSelectedFiles().length);
        }
        lastFile = fc.getSelectedFiles()[0].getParentFile();
    }

    @Override
    public void setEnabled(boolean enabled) {
        this.buttonAbrir.setEnabled(enabled);
        this.labelSeleccionados.setEnabled(enabled);
        this.buttonOpenFolder.setEnabled(enabled);
        super.setEnabled(enabled);
    }
}
